## **1. Pandas Series**

A Series is a one-dimensional labeled array capable of holding any data type. The axis labels are collectively called the index.

**Creating Series**

There are multiple ways to create a pandas Series:

In [ ]:
import numpy as np 
import pandas as pd

In [18]:
labels = ['a', 'b', 'c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {'a':10,'b':20,'c':30}

In [10]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [12]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [14]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [20]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

## **2. Pandas DataFrames**

**Creating a DataFrame**

In [ ]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [ ]:
df

In [ ]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns =columns)
df2

In [ ]:
df2

**Selection and Indexing of Columns**

In [ ]:
df2

In [ ]:
df2[["Name","City"]]

**Creating a new column**

In [ ]:
df2["Designation"] = ["Doctor","Eng.","Doctor","Eng."]

In [ ]:
df2

**Removing Columns**

In [ ]:
df2.drop(0,axis = 0)

In [ ]:
df2

**Selecting Rows**

In [ ]:
df2

In [ ]:
df2.loc[[0,1]]

In [ ]:
df.iloc[3]

**Selecting Subsets of Rows and Columns**

In [ ]:
df.loc[[0,1]][["City","Salary"]]

**Conditional Selection**

In [ ]:
df2

In [ ]:
#I only want to see those people whose age is above 30

In [ ]:
df2[df2["Age"] > 30]

In [ ]:
#I only want poeple whose age is above 30 and their city must be paris

In [ ]:
df2[(df2["Age"] > 30) & (df2["City"] == 'Paris')]

## **3. Missing Data**

**Finding Missing Data**

In [ ]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [ ]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
df.isna()

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

`isna` works Column-wise

In [ ]:
df.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [ ]:
df.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

**Removing Missing Data**

In [ ]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

`dropna` works Row-wise

In [ ]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [ ]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

`thresh` defines threshold by specifing minimum no of non NAN

In [ ]:
df.dropna(thresh=1)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
df.dropna(thresh=1)

**Filling the missing Data**

In [ ]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

`fillna` works Column-wise

In [ ]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [ ]:
values = {'A':0,'B':100,"C":300,'D':400}
df.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [ ]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

## **4. Merging, Joining & Concatination**

**Merging 2 dataframes**

In [ ]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [ ]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [ ]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [ ]:
pd.merge(employees,salaries,on='employee_id',how ='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [ ]:
pd.merge(employees,salaries,on='employee_id',how ='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [ ]:
pd.merge(employees,salaries,on='employee_id',how ='left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [ ]:
pd.merge(employees,salaries,on='employee_id',how ='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

**Concatination of 2 dataframes**

In [ ]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [ ]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [ ]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [ ]:
pd.concat([df2,df1])

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [ ]:
pd.concat([df1,df2],axis= 1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

**Joining 2 data frames**

In [ ]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [ ]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [ ]:
df2

   score
2     85
3     90
4     75

In [ ]:
df1.join(df2,how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

In [ ]:
df2.join(df1)

   score     name
2     85      Bob
3     90  Charlie
4     75      NaN

| Operation | Main Focus | How it aligns data |
| :--- | :--- | :--- |
| **Merge** | Columns | Common columns (Keys) ke zariye |
| **Join** | Indices | Row indexes ke zariye |
| **Concat** | Stacking | Rows ya columns ko seedha jorh dena |

## **5. GroupBy Aggregation**

**GroupBy**

In [ ]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)

In [ ]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

`.groupby()` just return the object which we cant see directly but internally it does grouping

In [ ]:
cat = df.groupby('Category')
cat

In [1]:
for i , v in cat:
    print(i)
    print(v)

NameError: name 'cat' is not defined

In [ ]:
# Group by Category and calculate the sum of Sales
cat = df.groupby('Category')['Sales'].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [ ]:
# Group by Store and calculate the sum of Sales
cat = df.groupby('Store')['Sales'].sum()
cat

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [ ]:
# Group by multiple columns
# Group by Category and Store
cat = df.groupby(['Category','Store'])['Sales'].sum()
cat

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

**Aggregation**

In [ ]:
df['Sales'].mean()
"""mean median min max count std """

187.5

In [ ]:
df['Sales'].agg(['sum', 'mean', 'min', 'max', 'count', 'std', 'median'])

sum       1500.000000
mean       187.500000
min        100.000000
max        300.000000
count        8.000000
std         66.062741
median     190.000000
Name: Sales, dtype: float64

## **6. Pivot Tables**

**Pivot Tables**

In [ ]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

In [ ]:
pd.pivot_table(df,values = "Sales",index = 'Region',columns="Product",aggfunc = 'median')

In [ ]:
pivot2 = pd.pivot_table(df, values=['Sales', 'Units'], index='Region', columns='Product')
pivot2

**Cross Tabs**

In [ ]:
pd.crosstab(df['Region'],df['Product'])

## **7. Operations**

**DataFrames Basic Operations**

In [ ]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [ ]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [ ]:
df1.shape

(5, 3)

In [ ]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [ ]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [ ]:
df.head()

In [ ]:
df.tail(10)

In [ ]:
df1['A'] + 10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

**DataFrames Applying Functions**

In [ ]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [ ]:
def square(x):
    return x ** 2

In [ ]:
df['D'] = df['B'].apply(square)

In [ ]:
df1['D'] = df1["B"].apply(lambda x : x**2)

In [ ]:
df1

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500